title: Little Orchard
description: Little Orchard - Coming Soon
baseurl: "/little-orchard"
url: "https://sps23.github.io"

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
